d = {'A': [4, 3, 2, 1], 'B': [], 'C': []}
print("Початковий стан: ", d)

print("\n-----Крок 1.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'B':", d['B'])
d['B'].append(move)
print("Проміжний стан: ", d)

print("\n----- Крок 2.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 3.")
print("Перемістити з 'B':", d['B'])
move = d['B'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 4.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'B':", d['B'])
d['B'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 5.")
print("Перемістити з 'C':", d['C'])
move = d['C'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'A':", d['A'])
d['A'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 6.")
print("Перемістити з 'C':", d['C'])
move = d['C'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'B':", d['B'])
d['B'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 7.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'B':", d['B'])
d['B'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 8.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 9.")
print("Перемістити з 'B':", d['B'])
move = d['B'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 10.")
print("Перемістити з 'B':", d['B'])
move = d['B'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'A':", d['A'])
d['A'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 11.")
print("Перемістити з 'C':", d['C'])
move = d['C'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'A':", d['A'])
d['A'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 12.")
print("Перемістити з 'B':", d['B'])
move = d['B'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 13.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'B':", d['B'])
d['B'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 14.")
print("Перемістити з 'A':", d['A'])
move = d['A'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Проміжний стан: ", d)

print("\n-----Крок 15.")
print("Перемістити з 'B':", d['B'])
move = d['B'].pop()
print(' '*32, "-->    диск", move, "  -->    до 'C':", d['C'])
d['C'].append(move)
print("Кінцевий стан: ", d)

